# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://eperg.github.io/
baseurl: /sustain/
title: Eper Gaboni
author: Eper Gaboni
description: Personal blog and resume
avatar: me.jpg
email: hello@epergaboni.com
github: eperg # username
twitter: epergaboni
linkedin: epergaboni

#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
